[theme]
# Couleurs primaires
primaryColor="#005ea2" # Bleu marine des remparts

# Couleur de fond principale
backgroundColor="#f0f2f6" # Gris très clair, comme le sable humide

# Couleur de fond secondaire (barre latérale, conteneurs)
secondaryBackgroundColor="#000000" # Blanc pur

# Couleur du texte
textColor="#ffffff" # Noir doux

# Police de caractères
font="sans serif"
